
[build]
  command = "bash ./deploy-netlify.sh"
  publish = "dist/public"
  functions = "dist/netlify-functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
